[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dashscope>=1.23.6",
    "fastapi>=0.115.13",
    "openai>=1.91.0",
    "uvicorn>=0.34.3",
]
